import { existsSync, readFileSync } from "node:fs";
import { builtinModules } from "node:module";
import path from "node:path";
import type { Plugin } from "vite";
import { defineConfig } from "vite";

// Load .env file if exists (without dotenv dependency)
function loadEnv(): Record<string, string> {
	const envPath = path.resolve(process.cwd(), ".env");
	if (!existsSync(envPath)) return {};

	const env: Record<string, string> = {};
	const content = readFileSync(envPath, "utf-8");
	for (const line of content.split("\n")) {
		const trimmed = line.trim();
		if (!trimmed || trimmed.startsWith("#")) continue;
		const [key, ...valueParts] = trimmed.split("=");
		if (key) env[key.trim()] = valueParts.join("=").trim();
	}
	return env;
}

const localEnv = loadEnv();
const pluginDir = localEnv.OBSIDIAN_PLUGIN_DIR;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE + ROLLDOWN
if you want to view the source, please visit the github repository of this plugin
*/
`;

function bannerPlugin(): Plugin {
	return {
		name: "banner-plugin",
		generateBundle(_options, bundle) {
			for (const chunk of Object.values(bundle)) {
				if (chunk.type === "chunk") {
					chunk.code = banner + chunk.code;
				}
			}
		},
	};
}

function devOutputLogPlugin(isProd: boolean, outDir: string): Plugin {
	let logged = false;
	return {
		name: "dev-output-log-plugin",
		buildStart() {
			if (isProd || logged) return;
			logged = true;
			if (pluginDir) {
				console.log(`\n[dev] Output to: ${outDir}/main.js`);
			} else {
				console.log("\n[dev] OBSIDIAN_PLUGIN_DIR not set. Output to: ./main.js");
				console.log("[dev] Create .env file with OBSIDIAN_PLUGIN_DIR to enable direct vault output.\n");
			}
		},
	};
}

export default defineConfig(({ mode }) => {
	const isProd = mode === "production";

	// Development mode: output directly to Vault if OBSIDIAN_PLUGIN_DIR is set
	const outDir = !isProd && pluginDir ? pluginDir : ".";

	return {
		plugins: [bannerPlugin(), devOutputLogPlugin(isProd, outDir)],
		build: {
			outDir,
			emptyOutDir: false,
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main.js",
			},
			sourcemap: isProd ? false : "inline",
			minify: isProd,
			rollupOptions: {
				external: [
					"obsidian",
					"electron",
					"@codemirror/autocomplete",
					"@codemirror/collab",
					"@codemirror/commands",
					"@codemirror/language",
					"@codemirror/lint",
					"@codemirror/search",
					"@codemirror/state",
					"@codemirror/view",
					"@lezer/common",
					"@lezer/highlight",
					"@lezer/lr",
					...builtinModules,
				],
				output: {
					entryFileNames: "main.js",
				},
			},
		},
		test: {
			globals: true,
			environment: "jsdom",
			include: ["src/**/*.test.ts"],
			coverage: {
				provider: "v8",
				reporter: ["text", "json", "html"],
				exclude: ["node_modules/", "src/**/*.test.ts"],
			},
			alias: {
				obsidian: path.resolve(__dirname, "src/__mocks__/obsidian.ts"),
			},
		},
	};
});
